### ISSUE TITLE
CLI option for browsing/opening existing gistup-generated gist

### ISSUE THREAD

**Issue by joyrexus** [mbostock/gistup#15]
For your standard github repos you can use [`git browse`](https://github.com/github/hub#git-browse) to open/browse the repo's remote via Github's web interface.  However, you can't use the `browse` subcommand to open gist-based repos (i.e., repos with remotes on `gist.github.com`).

I was expecting gistup's `--open` option to do this, but if you try running `gistup --open` in a directory that's already been gisted, you get ...

```
Reinitialized existing Git repository in /Users/jvoigt/Repos/gists/demo-gist/.git/
ERROR: the remote "origin" already exists.

Are you trying to run gistup in a directory that already has a git
repository?
```

Perhaps gistup could write a `.gist.url` file after initializing the gist's repo and look for this when the `--open` option is invoked?

FWIW, I'm currently using the following alias/hack for this purpose:

```
alias browse='open $(git config remote.origin.url | tr '\'':'\'' / | sed -e '\''s#git@#https://#'\'' -e '\''s/\.git$//'\'')'
```

**Comment by mbostock** [comment]
Thank you!
