### ISSUE TITLE
Gistup conflict with Git-stats?

### ISSUE THREAD

**Issue by auremoser** [mbostock/gistup#23]
### Context
My gistup was working so well to automate my [bl.ocks](bl.ocks.org/auremoser) and gists from the cli. But recently it started giving me errors, no longer works, and now I'm trying to figure out why.

### Process
I made a test directory to illustrate this, cd'd into it and typed this into terminal:
```
$ gistup --public -m 'Testing stuff'
```
### Expected result
Gistup creates my gist, with success, I tab to Chrome, rename the public gist and it populates on blocks momentarily. 

### Current result
```
Reinitialized existing Git repository in /Users/aurelia/Code/2015/gist-test/.git/
error Error: Invalid url field. This commit is not recorded into the git-stats history since you haven't added the remote url. You can import the previous commits using the git-stats-importer tool.

/usr/local/lib/node_modules/gistup/lib/gistup/unless.js:11
    throw error;
          ^
Error: git commit failed.
    at /usr/local/lib/node_modules/gistup/bin/gistup:152:65
    at ChildProcess.exithandler (child_process.js:646:7)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Process.ChildProcess._handle.onexit (child_process.js:823:5)
```

### Possible Issues
I'm on the same machine, same setup, same Github account as always, not pushing anything abnormal. All should be working.

I installed [git-stats](https://github.com/IonicaBizau/git-stats) a while back, circa the same time my gistup started failing; since it's cited in the error message, I wonder whether there's a conflict between the two (gistup <> gitstats)? There are no errors related to gistups in the git-stats repo.

Or maybe this is an error that someone has seen before and can help me debug/+1?

Thanks!

**Comment by mbostock** [comment]
This error looks to be the fault of git-stats. (It’s the one generating the error, apparently because it’s overly strict regarding the remote url.) I’m not able to help you debug it at the moment, but if you discover something that needs changing in gistup, please let me know.

**Comment by IonicaBizau** [comment]
@mbostock Indeed! I replied [here](https://github.com/IonicaBizau/git-stats/issues/64#issuecomment-135614040). :four_leaf_clover:
