### ISSUE TITLE
gist.github.com SSH timeout

### ISSUE THREAD

**Issue by SLeitgeb** [mbostock/gistup#39]
Gistup throws the following error when initializing a new gist:
```
Initialized empty Git repository in ~/example_01/.git/
[master (root-commit) SHA] Initial gistup commit.
 1 file changed, 308 insertions(+)
 create mode 100644 file.py
gist GIST_ID created!
https://gist.github.com/GIST_ID
~/.npm-global/lib/node_modules/gistup/lib/gistup/unless.js:11
    throw error;
    ^

Error: Command failed: git push -fu 'origin' master
ssh: connect to host gist.github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
```

Is suspect GitHub services might be the problem, since `tcptraceroute gist.github.com 22` eventually times out before reaching the destination.

Is it possible to use HTTPS over SSH in gistup or would you be interested in implementing it?

Similar issue found here: [https://stackoverflow.com/questions/60740289/ssh-connect-to-host-gist-github-com-port-22-operation-timed-out-fatal-could-n](https://stackoverflow.com/questions/60740289/ssh-connect-to-host-gist-github-com-port-22-operation-timed-out-fatal-could-n)

**Comment by mbostock** [comment]
I’m not interested but you’re welcome to fork this repository. Good luck!
